no_index: 
  directory: 
    - inc
    - t
generated_by: hand
distribution_type: module
version: 0.37
name: IO-All
author: Ingy döt Net <ingy@cpan.org>
license: perl
requires: 
  perl: 5.6.1
  IO::String: 0
abstract: IO::All of it to Graham and Damian!
